# Generated by Django 3.2.8 on 2021-10-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(max_length=150, verbose_name='Адрес')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
