# Generated by Django 3.2.8 on 2021-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(max_length=150, verbose_name='Адрес')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='CheckPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья для проверки',
                'verbose_name_plural': 'Статьи для проверки',
            },
        ),
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пользователь')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='FindAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Авторизированный Пользователь')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Авторизированный Пользователь',
                'verbose_name_plural': ' Авторизированные Пользователи',
            },
        ),
    ]
