# Generated by Django 3.2.8 on 2021-11-07 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
