# Generated by Django 3.2.8 on 2021-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_good',
            field=models.CharField(default='SOME STRING', max_length=150, verbose_name='Отредактированный адрес'),
        ),
    ]
