# Generated by Django 3.2.8 on 2021-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_url_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccount',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='findaccount',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
