# Generated by Django 3.2.8 on 2021-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_createaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Авторизированный Пользователь')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Авторизированный Пользователь',
                'verbose_name_plural': ' Авторизированных Пользователей',
            },
        ),
        migrations.AlterModelOptions(
            name='createaccount',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователей'},
        ),
    ]
